//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MtsCloneAPI.Context
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;

    public partial class Product
    {
        public int ID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> BrandID { get; set; }
        public decimal Price { get; set; }
        public string ModelName { get; set; }
        public string Description { get; set; }
        public string ProductImageLocation { get; set; }
        
        public virtual Brand Brand { get; set; }
        
        public virtual ProductType ProductType { get; set; }
    }
}
